### ISSUE TITLE
MEF IODataEndpoint should support GUID and have the loading mechanism defined inside the package

### ISSUE THREAD

**Issue by dfch** [dfch/biz.dfch.CS.System.Utilities#16]
Currently the actual loading of MEF endpoints is done inside the code of the application. However this should be external in the Utilities package.

Furtermore the plugin should support a GUID property and a mechanism to override the Priority.

See [Overriding MEF Metadata](http://blogs.msdn.com/b/dsplaisted/archive/2010/04/01/overriding-mef-metadata.aspx) for details.

**Comment by rufer7** [comment]
Because we moved web related code to [biz.dfch.CS.Web.Utilities](https://github.com/dfensgmbh/biz.dfch.CS.Web.Utilities) this issue was as well moved to [biz.dfch.CS.Web.Utilities](https://github.com/dfensgmbh/biz.dfch.CS.Web.Utilities). See dfensgmbh/biz.dfch.CS.Web.Utilities#2
