### ISSUE TITLE
MEF exports with IODataEndpoint or IODataEndpointData must support Version information

### ISSUE THREAD

**Issue by dfch** [dfch/biz.dfch.CS.System.Utilities#9]
Currently MEF endpoints that are loaded via the `IODataEndpoint` interface do not specify their version. When using these endpoints more intensively it will become difficult to manage or detect their versions.

Therefore it is suggested to either implement a static property on `IODataEndpointData` which specifies the version of the assembly/plugin or to add a method/property to `IODataEndpoint` that returns the version.

The disadvantage of having the version information supplied in `IODataEndpointData` is that it is *static*, but it is then very obvious (within the data annotation) which version the plugin is supposed to have.

If the version information was supplied via `IODataEndpoint` then it could be read from the assembly or somewhere else (which could lead to a more consistent version scheme and could be detectable from the *outside* via file information).

**Both of these suggested changes are *breaking* changes!**

**Comment by dfch** [comment]
@rufer7 what do you think of this? 
The downside is, that we have that `IODataEndpoint` inside the utilities package so everyone upgrading this package for other reasons will run into that breaking change.
I know that breaking changes are not the way to go, but this is very early in the dev process of that component, so I think we should go for it.

**Comment by rufer7** [comment]
@dfch Seems to be a good point providing the version in IODataEndpoint. Another option could be reading the assembly version itself. The disadvantage is, that with this apptoach the version gets increased with every build. Exposing the version by a method or field seems to be more flexible. I would suggest taking the approach you suggested. Breaking changes in early development state should not be the reason for not doing it.
